export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const ADD_PROFILE = 'ADD_PROFILE';

export const REMOVE_PROFILE = "REMOVE_PROFILE"
export const REMOVE_DB_PROFILE = 'REMOVE_DB_PROFILE';
export const SET_DB_PROFILE = 'SET_DB_PROFILE';

export const FETCH_SYS_SETTINGS = 'FETCH_SYS_SETTINGS';
export const ADD_SYS_SETTINGS = 'ADD_SYS_SETTINGS';
export const EDIT_SYS_SETTINGS = 'EDIT_SYS_SETTINGS';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const VIEW_CUSTOMER = 'VIEW_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';

export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const FETCH_CUSTOMER_FAILED = 'FETCH_CUSTOMER_FAILED';

export const FETCH_DUE_WORKORDER = 'FETCH_DUE_WORKORDER';
export const FETCH_TODAY_WORKORDER = 'FETCH_TODAY_WORKORDER';
export const FETCH_OPEN_WORKORDER  = 'FETCH_OPEN_WORKORDER';

export const FETCH_TECH_LOAD = 'FETCH_TECH_LOAD';
export const FETCH_CUSTOMER_WORKORDER = 'FETCH_CUSTOMER_WORKORDER';
export const CLOSE_WORKORDER = 'CLOSE_WORKORDER';

export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const VIEW_SERVICE = 'VIEW_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const FETCH_SERVICE = 'FETCH_SERVICE';
export const FETCH_SERVICE_FAILED = 'FETCH_SERVICE_FAILED';

export const ADD_TECH = 'ADD_TECH';
export const EDIT_TECH = 'EDIT_TECH';
export const VIEW_TECH = 'VIEW_TECH';
export const DELETE_TECH = 'DELETE_TECH';

export const FETCH_TECH = 'FETCH_TECH';
export const FETCH_TECH_FAILED = 'FETCH_TECH_FAILED';

export const FETCH_WORKORDER = 'FETCH_WORKORDER';
export const ADD_WORKORDER = 'ADD_WORKORDER';
export const EDIT_WORKORDER = 'EDIT_WORKORDER';
export const DELETE_WORKORDER = 'DELETE_WORKORDER';

export const FETCH_WORKORDER_DTL = 'FETCH_WORKORDER_DTL';
export const ADD_WORKORDER_DTL = 'ADD_WORKORDER_DTL';
export const EDIT_WORKORDER_DTL = 'EDIT_WORKORDER_DTL';
export const DELETE_WORKORDER_DTL = 'DELETE_WORKORDER_DTL';

export const FETCH_WORKORDER_PARTS  = 'FETCH_WORKORDER_PARTS';
export const ADD_WORKORDER_PARTS    = 'ADD_WORKORDER_PARTS';
export const EDIT_WORKORDER_PART    = 'EDIT_WORKORDER_PARTS';
export const DELETE_WORKORDER_PARTS = 'DELETE_WORKORDER_PARTS';











